// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserTag = "UserTags"

// UserTag mapped from table <UserTags>
type UserTag struct {
	UserID string `gorm:"column:user_id;type:varchar(255);primaryKey" json:"user_id"`
	TagID  string `gorm:"column:tag_id;type:varchar(255);primaryKey;index:tag_id,priority:1" json:"tag_id"`
}

// TableName UserTag's table name
func (*UserTag) TableName() string {
	return TableNameUserTag
}
